

include $(APPDIR)/Make.defs

# SD Card mounter built-in application info

PROGNAME  = $(CONFIG_INSPACE_SDCARD_PROGNAME)
PRIORITY  = $(CONFIG_INSPACE_SDCARD_PRIORITY)
STACKSIZE = $(CONFIG_INSPACE_SDCARD_STACKSIZE)
MODULE    = $(CONFIG_INSPACE_SDCARD)

# SD Card mounter

MAINSRC = sdcard_mounter_main.c

include $(APPDIR)/Application.mk
