

include $(APPDIR)/Make.defs

# Mocking built-in application info

PROGNAME  = $(CONFIG_INSPACE_MOCKING_PROGNAME)
PRIORITY  = $(CONFIG_INSPACE_MOCKING_PRIORITY)
STACKSIZE = $(CONFIG_INSPACE_MOCKING_STACKSIZE)
MODULE    = $(CONFIG_INSPACE_MOCKING)

# Sensor mocking application

MAINSRC = mocking_main.c

include $(APPDIR)/Application.mk
